### ISSUE TITLE
type agnostic value pipe missing

### ISSUE THREAD

**Issue by elegon32** [joanllenas/ngx-remotedata#10]
Hi! :)

you intended:
```
The InProgress class can contain a value of the same T type as the Success class. 
Useful when you want to use the last Success value while the new data is being fetched.
```

But when using that same inProgressValue inside a template, it currently is necessary to duplicate access to the value:
```
<h4 *ngIf="remoteData | isInProgress" style="color: green">
  {{ remoteData | inProgressValue }}
</h4>
<h4 *ngIf="remoteData | isSuccess" style="color: green">
  {{ remoteData | successValue }}
</h4>
```
Wouldnt it be nice to have an agnostic value pipe? Like so:
```
<h4 *ngIf="remoteData | hasValue" style="color: green">
  {{ remoteData | successOrProgressValue }}
</h4>
```

**Comment by joanllenas** [comment]
Hi @elegon32 ,
I never thought about that, but that'd indeed be a desirable feature to have.

I'll label it as `good first issue` and `help wanted` and if nothing happens in a week or so I'll implement it myself.

Thanks for the suggestion!

**Comment by joanllenas** [comment]
Closed via [pull/11](https://github.com/joanllenas/ngx-remotedata/pull/11)
The release is ready.

Thanks again!
