### ISSUE TITLE
Failure with value...

### ISSUE THREAD

**Issue by elegon32** [joanllenas/ngx-remotedata#12]
Ok...

I have a case, where the backend responds with an error message, but the previous state ist still valid (or it responds with the current state but adds an error-message to the response)
So the user shoud see the old values exactly like in the "InProgress" state - but also the error message...

This feature would have some implications...
It could be implemented as an upgrade of the Failure class (add "val")
But perhaps it would be better to have a separate state for this, ie InError<T> (with regard to it behaving like a transition as InProgress but including both: val and err).

What do you think?

**Comment by joanllenas** [comment]
Ok, I understand your use case. Makes sense.
I see this more as a `Failure<T, E>` upgrade than a new RemoteData type.
It's a breaking change, I'll take a look during the week.
As always PRs are welcomed.

Thanks!

**Comment by joanllenas** [comment]
- Closed via [pull/13](https://github.com/joanllenas/ngx-remotedata/pull/13)
- Release notes: https://github.com/joanllenas/ngx-remotedata/releases/tag/v3.0.0

Thanks @elegon32 !
