### ISSUE TITLE
NotAsked breaks type checking and inference

### ISSUE THREAD

**Issue by toverux** [joanllenas/ngx-remotedata#3]
This is an issue with TypeScript (3.4.5) that I do not fully understand.

Let's begin with the current `RemoteData<T, E>` and `NotAsked` definition:

```ts
export declare class NotAsked {
}

export declare type RemoteData<T, E = string> = NotAsked | InProgress<T> | Failure<E> | Success<T>;
```

With those types, I'm able to do an incorrect assignation:

```ts
type AnObject = { smth: 42 };

let a: RemoteData<AnObject>;
const b: RemoteData<42> = smth();

a = b; // works
```

Type comparison between `RemoteData` objects is broken, I figured that out when using an incorrect payload in `Success`, and that I had no type error.

I tried modifying the declaration of `NotAsked` so it become generic, too:

```ts
export declare class NotAsked<T> {
}

export declare type RemoteData<T, E = string> = NotAsked<T> | InProgress<T> | Failure<E> | Success<T>;
```

Exact same behavior.

But then I tried this (please notice that I've removed the generic I added):

```ts
export declare class NotAsked {
    private thisPropertyFixesTypeScriptTypeChecking;
}

export declare type RemoteData<T, E = string> = NotAsked | InProgress<T> | Failure<E> | Success<T>;
```

And boom, we get the expected behavior!

```ts
let a: RemoteData<AnObject>;
const b: RemoteData<42> = smth();

a = b; // boom
// error TS2322: Type 'RemoteData<42, string>' is not assignable to type 'RemoteData<AnObject, string>'.
//     Type 'InProgress<42>' is not assignable to type 'RemoteData<AnObject, string>'.
//     Type 'InProgress<42>' is not assignable to type 'InProgress<AnObject>'.
//     Type '42' is not assignable to type 'AnObject'.
```

Somehow, the empty `NotAsked` class breaks TypeScript type-cheking on generics. Don't ask me why.

Btw, thanks for your work! I thought about such a pattern myself and discovered this implementation wandering around your profile, being a long-time user of ngx-date-fns. I'm now trying it into one of my codebases, but unfortunately, I stumbled upon this strange behavior that prevents me from having correct type inference and cheking where I use ngx-remotedata. Is it possible to workaround the problem like I did here, right into the library?

**Comment by joanllenas** [comment]
Hi @toverux !
that's weird indeed...
Thank's for investigating the issue, I'll try to understand why this is happening and fix the issue.
Cheers!

**Comment by joanllenas** [comment]
Hey @toverux ,
It ended up being a major release.

Take a look here: https://github.com/joanllenas/ngx-remotedata/releases/tag/v2.0.0
Let me know if you feel like something is still missing.

Thanks for reporting,
cheers!

**Comment by joanllenas** [comment]
Fixed via https://github.com/joanllenas/ngx-remotedata/commit/758635697dae38c32f22249c19e33042d60be7b5

Closing.
