### ISSUE TITLE
Latest patch version is a breaking change for Angular 13

### ISSUE THREAD

**Issue by koenigderluegner** [joanllenas/ngx-remotedata#46]
Patch version 7.0.1 breaks usage of this package in Angular 13 - please consider it releasing as 8.0.0 or fixing it in 7.0.2 (or both)

Error: 
TypeError: Cannot create property 'message' on string '...\node_modules\ngx-remotedata\fesm2015\ngx-remotedata.mjs: This application depends upon a library published using Angular version 14.0.7, which requires Angular version 14.0.0 or newer to
 work correctly.
Consider upgrading your application to use a more recent version of Angular.

**Comment by joanllenas** [comment]
Thanks for reporting @koenigderluegner 
Looking into it right now.

**Comment by joanllenas** [comment]
@koenigderluegner you can now install [v7.0.2](https://www.npmjs.com/package/ngx-remotedata/v/7.0.2)
I have also released v8 for Angular 14.

**Comment by koenigderluegner** [comment]
Thanks for reacting so quickly. Much appreciated!
