### ISSUE TITLE
stateManagement -> de/serialization

### ISSUE THREAD

**Issue by elegon32** [joanllenas/ngx-remotedata#9]
when using this with redux, how to serialize/deserialize state - in order to create snapshots for mocks, localStorage etc...
All instanceof checks will stop working after reading the state from json and so would all of the pipes stop working. Or am i missing some point?
How do you sovle this?

**Comment by joanllenas** [comment]
Hi @elegon32 ,
I added an example of ngrx store rehydration, look at this file: https://github.com/joanllenas/ngx-remotedata/blob/master/src/app/app.module.ts
